Repository statkraft/shyft, pull requests merged in 2018-05, with the labels that each got.

#271 KRLS service
  api/boostpython/api_dtss.cpp
  api/python/api.python.vcxproj
  api/python/hbv_stack.python.vcxproj
  api/python/pt_gs_k.python.vcxproj
  api/python/pt_hps_k.python.vcxproj
  api/python/pt_hs_k.python.vcxproj
  api/python/pt_ss_k.python.vcxproj
  core/CMakeLists.txt
  core/core.vcxproj
  core/core.vcxproj.filters
  core/dtss.cpp
  core/dtss.h
  core/dtss_client.cpp
  core/dtss_client.h
  core/dtss_db.h
  core/dtss_krls.h
  core/dtss_msg.h
  core/dtss_url.h
  core/predictions.h
  core/time_series_info.h
  core/time_series_serialization.cpp
  shyft/tests/api/test_dtss.py
  test/dtss_stress_test.cpp
  test/dtss_test.cpp
Labels: enhancement

#278 Tune flow n step
  api/boostpython/expose.h
  build_support/win_build_dependencies.sh
  conda_recipe/conda_build_config.yaml
  conda_recipe/meta.yaml
  core/model_state_tuning.h
  core/region_model.h
  shyft/tests/api/test_region_model_stacks.py
  test/cell_builder_test.cpp
Labels: enhancement

#284 implemented trim and diff_units to utcperiod
  api/boostpython/api_utctime.cpp
  core/utctime_utilities.cpp
  core/utctime_utilities.h
  shyft/tests/api/test_calendar_and_time.py
  test/utctime_utilities_test.cpp
Labels: enhancement

#286 updated cmake, started updating readme
  CMakeLists.txt
  README.md
  api/boostpython/CMakeLists.txt
Labels: enhancement

#288 TsVector from python list convert incl. tests
  CMakeLists.txt
  api/boostpython/api_time_series.cpp
  api/boostpython/api_vectors.cpp
  core/time_series_dd.h
  shyft/tests/api/test_vector_create.py
Labels: enhancement

#293 Fix intersection and tune flow
  .travis.yml
  api/boostpython/api_utctime.cpp
  core/model_state_tuning.h
  shyft/tests/api/test_calendar_and_time.py
  shyft/tests/api/test_region_model_stacks.py
Labels: bug, enhancement

#295 skaugen-snow: fixup swe so that it reports mm over the cell-area
  api/boostpython/api_skaugen.cpp
  core/pt_ss_k_cell_model.h
  core/skaugen.h
  test/pt_ss_k_test.cpp
  test/skaugen_test.cpp
Labels: bug

#298 skaugen snow: adjust reported state swe and free water to cell-area
  core/pt_ss_k_cell_model.h
  core/skaugen.h
Labels: enhancement

#297 Cf region model
  shyft/repository/netcdf/cf_region_model_repository.py
  shyft/repository/netcdf/utils.py
  shyft/tests/test_cf_region_model_repository.py
Labels: enhancement
