Repository statkraft/shyft, pull requests merged in 2018-08, with the labels that each got.

#319 Minor bugfixes, doc-strings and cleanup
  api/boostpython/api_geo_cell_data.cpp
  api/boostpython/expose.h
  shyft/tests/api/test_geo_cell_data.py
  shyft/tests/api/test_region_model_stacks.py
  shyft/tests/test_gfs_repository.py
Labels: bug, enhancement

#313 URL fixes and improvments
  VERSION
  api/boostpython/api_dtss.cpp
  core/dtss_url.h
  shyft/api/__init__.py
  shyft/tests/api/test_dtss.py
  shyft/tests/api/test_url_utils.py
  test/CMakeLists.txt
  test/dtss_stress_test.cpp
  test/dtss_test.cpp
  test/dtss_url_test.cpp
  test/test.vcxproj
  test/test.vcxproj.filters
Labels: enhancement

#321 Clone opt model fix
  core/model_calibration.h
  core/region_model.h
  shyft/tests/api/test_region_model_stacks.py
Labels: bug

#322 Qm speed improvements
  core/time_series_qm.h
  shyft/tests/api/test_quantile_mapping.py
  test/qm_test.cpp
Labels: enhancement

#325 boost 1.68 armadillo 9.x updates
  CMakeLists.txt
  api/boostpython/CMakeLists.txt
  api/boostpython/api_time_series.cpp
  api/boostpython/api_utctime.cpp
  api/boostpython/expose.h
  build_support/build_dependencies.sh
  build_support/win_build_dependencies.sh
  buildconfig.yaml
  core/utctime_utilities.cpp
  test/dtss_stress_test.cpp
  test/utctime_utilities_test.cpp
Labels: enhancement

#329 resolve issue with str of time outside range corresponding to +-9999y
  api/boostpython/api_utctime.cpp
  core/utctime_utilities.cpp
  core/utctime_utilities.h
  shyft/tests/api/test_calendar_and_time.py
Labels: bug

#326 selector_ts
  shyft/pyapi/__init__.py
  shyft/pyapi/selector_ts.py
  shyft/tests/pyapi/__init__.py
  shyft/tests/pyapi/test_selector_ts.py
Labels: enhancement

#327 Move krls predictors stored in a dtss server
  core/dtss_krls.h
  test/CMakeLists.txt
  test/dtss_krls_pred_db_test.cpp
  test/dtss_test.cpp
  test/test.vcxproj
  test/test.vcxproj.filters
Labels: enhancement

#334 allowing union of data of the same source type provided by different …
  shyft/repository/geo_ts_repository_collection.py
  shyft/tests/test_geo_ts_repository_collection.py
Labels: enhancement
