Repository statkraft/shyft, pull requests merged in 2019-02, with the labels that each got.

#401 snow swe and sca collection for ptssk discharge_collector.
  core/pt_ss_k_cell_model.h
Labels: bug

#402 derivative_ts: fixed missing bind-info propagation
  core/time_series_dd.cpp
  shyft/tests/api/test_time_series_derivative.py
Labels: bug

#391 Provide dtss with result period clip
  api/boostpython/api_dtss.cpp
  core/dtss.h
  core/dtss_client.cpp
  core/dtss_client.h
  core/dtss_msg.h
  core/time_series_dd.cpp
  core/time_series_dd.h
  shyft/tests/api/test_dtss.py
  test/CMakeLists.txt
  test/dtss_test.cpp
  test/test.cbp
  test/test.vcxproj
  test/test.vcxproj.filters
  test/time_series_clip_to_period_test.cpp
Labels: enhancement, ready

#406 time_axis of n periods, constructed fromn+1 time-points, succeeds or throws
  core/time_axis.h
  test/time_axis_test.cpp
Labels: bug, enhancement

#407 TimeSeries.accumulate(time_axis), handle nan anywhere
  core/time_series_dd.h
  test/CMakeLists.txt
  test/test.cbp
  test/test.vcxproj
  test/test.vcxproj.filters
  test/time_series_test_accumulate.cpp
Labels: bug

#408 Add logarithm operator to time-series and ts-vector
  api/boostpython/api_time_series.cpp
  core/gamma_snow.h
  core/kirchner.h
  core/time_series.h
  core/time_series_dd.cpp
  core/time_series_dd.h
  shyft/tests/api/test_time_series.py
  test/time_series_test.cpp
Labels: enhancement
