Repository statkraft/shyft, pull requests merged in 2019-03, with the labels that each got.

#410 Ignore dst in calendar if effective delta-t is <= dst-shift
  .gitlab-ci.yml
  build_support/win_conda_deploy.cmd
  core/utctime_utilities.cpp
  core/utctime_utilities.h
  test/utctime_utilities_test.cpp
Labels: bug, enhancement

#412 Eval speed up
  api/boostpython/api_time_series.cpp
  core/CMakeLists.txt
  core/core.cbp
  core/core.vcxproj
  core/core.vcxproj.filters
  core/expression_serialization.h
  core/time_series_dd.cpp
  core/time_series_dd.h
  core/time_series_dd_eval.cpp
  core/time_series_serialization.cpp
  shyft/tests/api/test_bucket_ts.py
  test/CMakeLists.txt
  test/serialization_test.cpp
  test/test.cbp
  test/test.vcxproj
  test/test.vcxproj.filters
  test/time_series_bucket_test.cpp
  test/time_series_eval_test.cpp
Labels: enhancement, ready

#413 added time shift to compensate for the derivative
  core/time_series_dd.cpp
  shyft/tests/api/test_bucket_ts.py
  test/time_series_bucket_test.cpp
Labels: bug, enhancement

#416 Fix ts.extend bug for break-point time-series
  core/time_series_dd.cpp
  shyft/tests/api/test_time_series.py
  test/CMakeLists.txt
  test/test.cbp
  test/test.vcxproj
  test/test.vcxproj.filters
  test/time_series_extend_test.cpp
Labels: bug

#417 Filter kernel alignment in convolve_w_ts
  api/boostpython/api_time_series.cpp
  core/time_series.h
  shyft/api/__init__.py
  shyft/tests/api/test_convolve_ts.py
  test/time_series_eval_test.cpp
  test/time_series_test.cpp
Labels: enhancement
